/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import adminfolder.admindash;
import config.dbConnector;
import frontdeskdash.dashfront;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/**
 *
 * @author wangs
 */
public class applicationform extends javax.swing.JFrame {

    /**
     * Creates new form applicationform
     */
    public applicationform() {
        initComponents();
    }
    
   public static String afsname, alsname;
    
    public boolean fname_alname(){
        dbConnector dbc = new dbConnector();
        
        try{
        String query = "SELECT * FROM applicantstab WHERE fname ='"+afname.getText()+"' ";
            ResultSet resultSet = dbc.getData(query);
       
         
            if(resultSet.next()){
                afsname = resultSet.getString("fname");  
                if(afsname.equals(afname.getText())){
                    JOptionPane.showMessageDialog(null, "first name exist!");
                    alname.setText("");         
                } 
                return true;
            }else{
                return false;
            }
            
            
        
        }catch(SQLException e){
            System.out.println(""+e);
            return false;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        bbm = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        bb = new javax.swing.JButton();
        uni1 = new javax.swing.JComboBox<>();
        agend = new javax.swing.JComboBox<>();
        ayear = new javax.swing.JTextField();
        afads = new javax.swing.JTextField();
        amads = new javax.swing.JTextField();
        afname = new javax.swing.JTextField();
        alname = new javax.swing.JTextField();
        anitial = new javax.swing.JTextField();
        aphone = new javax.swing.JTextField();
        aemailadd = new javax.swing.JTextField();
        aadress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(919, 591));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(null);

        jPanel1.setLayout(null);

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("BERGEN SCHOLARSHIP UNIVERSITY");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(240, 10, 470, 20);

        bbm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/icons8-back-50.png"))); // NOI18N
        bbm.setText("jButton2");
        bbm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bbmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bbmMouseExited(evt);
            }
        });
        bbm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbmActionPerformed(evt);
            }
        });
        jPanel1.add(bbm);
        bbm.setBounds(820, 10, 93, 29);

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Mothers Name:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(450, 170, 120, 22);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Fathers Name:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(450, 210, 120, 22);

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Year and course:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(430, 250, 150, 22);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Gender:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(490, 290, 70, 22);

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Scholarship type:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(430, 330, 150, 22);

        bb.setText("Add Applicants");
        bb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bbMouseExited(evt);
            }
        });
        bb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbActionPerformed(evt);
            }
        });
        jPanel1.add(bb);
        bb.setBounds(540, 370, 140, 29);

        uni1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unifast", "Ched", "Smart" }));
        jPanel1.add(uni1);
        uni1.setBounds(580, 330, 80, 26);

        agend.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel1.add(agend);
        agend.setBounds(570, 290, 81, 26);
        jPanel1.add(ayear);
        ayear.setBounds(570, 250, 170, 26);
        jPanel1.add(afads);
        afads.setBounds(570, 210, 170, 26);

        amads.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amadsActionPerformed(evt);
            }
        });
        jPanel1.add(amads);
        amads.setBounds(570, 170, 170, 26);
        jPanel1.add(afname);
        afname.setBounds(240, 170, 170, 26);
        jPanel1.add(alname);
        alname.setBounds(240, 210, 170, 26);
        jPanel1.add(anitial);
        anitial.setBounds(240, 250, 170, 26);
        jPanel1.add(aphone);
        aphone.setBounds(240, 290, 170, 26);

        aemailadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aemailaddActionPerformed(evt);
            }
        });
        jPanel1.add(aemailadd);
        aemailadd.setBounds(240, 330, 170, 26);

        aadress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aadressActionPerformed(evt);
            }
        });
        jPanel1.add(aadress);
        aadress.setBounds(240, 370, 170, 26);

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Email Adress:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(130, 340, 110, 22);

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Adress:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(170, 370, 90, 22);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Phone #:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(160, 290, 90, 22);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Middle Initial:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(130, 250, 110, 22);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Lastname:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(160, 210, 90, 22);

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("FirstName:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(160, 170, 90, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Brown and Beige Blank Notes Landscape A4 Document_1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 920, 590);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(0, 0, 920, 590);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 920, 590);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aemailaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aemailaddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aemailaddActionPerformed

    private void amadsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amadsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amadsActionPerformed

    private void bbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbActionPerformed
   
        
        
        if(afname.getText().isEmpty() || alname.getText().isEmpty() 
                || anitial.getText().isEmpty() || aphone.getText().isEmpty() 
                || aemailadd.getText().isEmpty() || aadress.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "All fields are required!");
            
        }else{
        
        dbConnector dbc = new dbConnector();
        
        try{
            
            if(dbc.insertData("INSERT INTO applicantstab(fname, lname, middle_initial, contact_number, email_address, adress, mother_name, father_name, year_course, gender, scholarship_type, status)"
                + "Values ('"+afname.getText()+"', '"+alname.getText()+"', '"+anitial.getText()+"' , '"+aphone.getText()+"', '"+aemailadd.getText()+"', "
                        + " '"+aadress.getText()+"', '"+amads.getText()+"', '"+afads.getText()+"', '"+ayear.getText()+"', "
                        + " '"+agend.getSelectedItem()+"','"+uni1.getSelectedItem()+"' , 'Pending' ) ")){ 
                JOptionPane.showMessageDialog(null, "Applicants Added");
        
            }else{
            
                JOptionPane.showMessageDialog(null, "Connection Error");
        }   
         
        
        
        }catch (HeadlessException e){
        
            System.out.println(e);
        
        }  
        this.dispose();     
        }
    }//GEN-LAST:event_bbActionPerformed

    private void aadressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aadressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aadressActionPerformed

    private void bbmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbmActionPerformed
       dashfront ads = new dashfront();
       ads.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_bbmActionPerformed

    private void bbmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbmMouseEntered
         bbm.setBackground(Color.red);
    }//GEN-LAST:event_bbmMouseEntered

    private void bbmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbmMouseExited
         bbm.setBackground(Color.white);
    }//GEN-LAST:event_bbmMouseExited

    private void bbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbMouseEntered
         bb.setBackground(Color.green);
    }//GEN-LAST:event_bbMouseEntered

    private void bbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbMouseExited
        bb.setBackground(Color.white);
    }//GEN-LAST:event_bbMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(applicationform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(applicationform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(applicationform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(applicationform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new applicationform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aadress;
    private javax.swing.JTextField aemailadd;
    private javax.swing.JTextField afads;
    private javax.swing.JTextField afname;
    private javax.swing.JComboBox<String> agend;
    private javax.swing.JTextField alname;
    private javax.swing.JTextField amads;
    private javax.swing.JTextField anitial;
    private javax.swing.JTextField aphone;
    private javax.swing.JTextField ayear;
    private javax.swing.JButton bb;
    private javax.swing.JButton bbm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> uni1;
    // End of variables declaration//GEN-END:variables
}
