
package adminfolder;

import config.dbConnector;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import static login.registerform.passwordHash;


public class adminapp extends javax.swing.JFrame {

    
    public adminapp() {
        initComponents();
        table_load2();
        
        
    }
    
    public void table_load2(){
         
         dbConnector dbc = new dbConnector();
    
        try {
            
        
            DefaultTableModel dt = (DefaultTableModel) tabs2.getModel();
            dt.setRowCount(0);
            
            String query = ("SELECT * FROM applicantstab");
            ResultSet rs = dbc.getData(query);
            
            while(rs.next()){
            
                Vector v = new Vector();
                
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                v.add(rs.getString(5));
                v.add(rs.getString(6));
                v.add(rs.getString(7));
                v.add(rs.getString(8));
                v.add(rs.getString(9));            
                v.add(rs.getString(10));
                v.add(rs.getString(11));
                v.add(rs.getString(12)); 
                v.add(rs.getString(13)); 
                
                
                
                dt.addRow(v);
            
            }
       
        
        }catch (SQLException e){
            
            System.out.println(e);
        
        }
    
    }
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nomore = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabs2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        applast = new javax.swing.JTextField();
        appfirst = new javax.swing.JTextField();
        appcont = new javax.swing.JTextField();
        appemail = new javax.swing.JTextField();
        appaddress = new javax.swing.JTextField();
        appmads = new javax.swing.JTextField();
        apppads = new javax.swing.JTextField();
        appyear = new javax.swing.JTextField();
        appmid = new javax.swing.JTextField();
        apptype = new javax.swing.JComboBox<>();
        appstats = new javax.swing.JComboBox<>();
        appgend = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        bbk = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        appid = new javax.swing.JLabel();
        yet = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Search");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(190, 0, 47, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Registered Applicants");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(400, 20, 259, 29);

        nomore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomoreActionPerformed(evt);
            }
        });
        nomore.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nomoreKeyReleased(evt);
            }
        });
        jPanel1.add(nomore);
        nomore.setBounds(240, 0, 150, 26);

        tabs2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Applicants ID", "fname", "lname", "middle_name", "contact_number", "email_address", "address", "mother_name", "father_name", "year_course", "gender", "scholarship_type", "Status"
            }
        ));
        tabs2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabs2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabs2);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 460, 1086, 237);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("ID");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(300, 130, 17, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Scholarship type");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(470, 300, 110, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("LastName:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(250, 210, 80, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("FirstName:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(250, 170, 80, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("MiddleName:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(240, 240, 80, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("ContactNumber:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(210, 280, 110, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Email Address:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(230, 310, 90, 17);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Mother Name:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(490, 160, 100, 17);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Father Name:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(500, 190, 100, 17);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Year & course:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(490, 220, 100, 17);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Address:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(260, 340, 60, 17);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Status");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(520, 340, 60, 17);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("gender");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(530, 260, 50, 17);
        jPanel1.add(applast);
        applast.setBounds(320, 210, 140, 26);
        jPanel1.add(appfirst);
        appfirst.setBounds(320, 170, 140, 26);
        jPanel1.add(appcont);
        appcont.setBounds(320, 270, 140, 26);
        jPanel1.add(appemail);
        appemail.setBounds(320, 310, 140, 26);
        jPanel1.add(appaddress);
        appaddress.setBounds(320, 340, 140, 26);
        jPanel1.add(appmads);
        appmads.setBounds(580, 160, 140, 26);
        jPanel1.add(apppads);
        apppads.setBounds(580, 190, 140, 26);
        jPanel1.add(appyear);
        appyear.setBounds(580, 220, 140, 26);
        jPanel1.add(appmid);
        appmid.setBounds(320, 240, 140, 26);

        apptype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ched", "Unifast", "Smart" }));
        jPanel1.add(apptype);
        apptype.setBounds(580, 300, 80, 26);

        appstats.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Approved", "Decline" }));
        jPanel1.add(appstats);
        appstats.setBounds(570, 340, 100, 26);

        appgend.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        appgend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appgendActionPerformed(evt);
            }
        });
        jPanel1.add(appgend);
        appgend.setBounds(580, 260, 81, 26);

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(650, 380, 93, 29);

        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(410, 380, 85, 29);

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(520, 380, 93, 29);

        bbk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/icons8-back-50.png"))); // NOI18N
        bbk.setText("jButton5");
        bbk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bbkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bbkMouseExited(evt);
            }
        });
        bbk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbkActionPerformed(evt);
            }
        });
        jPanel1.add(bbk);
        bbk.setBounds(940, 30, 80, 40);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/icons8-students-100.png"))); // NOI18N
        jLabel17.setText("Manage Students");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(390, 40, 270, 22);

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(300, 380, 69, 29);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton6.setText("Print All");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(800, 410, 110, 40);

        appid.setText("jLabel2");
        jPanel1.add(appid);
        appid.setBounds(340, 130, 51, 20);

        yet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Brown and Beige Blank Notes Landscape A4 Document_1.jpg"))); // NOI18N
        yet.setText("jLabel2");
        jPanel1.add(yet);
        yet.setBounds(0, -10, 1090, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabs2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabs2MouseClicked
        int r = tabs2.getSelectedRow();
        
        String id = tabs2.getValueAt(r, 0).toString();
        String firstname = tabs2.getValueAt(r, 1).toString();
        String lastname = tabs2.getValueAt(r, 2).toString();
        String middlename = tabs2.getValueAt(r, 3).toString();
        String contactnumber = tabs2.getValueAt(r, 4).toString();
        String email = tabs2.getValueAt(r, 5).toString(); 
        String address = tabs2.getValueAt(r, 6).toString();
        String mothername = tabs2.getValueAt(r, 7).toString();
        String fathername = tabs2.getValueAt(r, 8).toString();
        String year = tabs2.getValueAt(r, 9).toString();
        String gender = tabs2.getValueAt(r, 10).toString();
        String account_type = tabs2.getValueAt(r, 11).toString();
        String stat = tabs2.getValueAt(r, 12).toString();
                
        
        appid.setText(id);
        appfirst.setText(firstname);
        applast.setText(lastname);
        appmid.setText(middlename);
        appcont.setText(contactnumber);
        appemail.setText(email);
        appaddress.setText(address);
        appmads.setText(mothername);
        apppads.setText(fathername);
        appyear.setText(year);
        appgend.setSelectedItem(gender);
        apptype.setSelectedItem(account_type); 
        appstats.setSelectedItem(stat); 
        
    }//GEN-LAST:event_tabs2MouseClicked

    private void nomoreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomoreKeyReleased
        String name = nomore.getText();

        dbConnector dbc = new dbConnector();

        try {

            DefaultTableModel dt = (DefaultTableModel) tabs2.getModel();
            dt.setRowCount(0);

            String query = ("SELECT * FROM applicantstab WHERE lname LIKE '%"+name+"%' ");
            ResultSet rs = dbc.getData(query);

            while(rs.next()){

                Vector v = new Vector();

                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                v.add(rs.getString(5));
                v.add(rs.getString(6));
                v.add(rs.getString(7));
                v.add(rs.getString(8));
                v.add(rs.getString(9));
                v.add(rs.getString(10));
                v.add(rs.getString(11));
                v.add(rs.getString(12));
                v.add(rs.getString(13));
                    
                dt.addRow(v);

            }

        }catch (Exception e){

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_nomoreKeyReleased

    private void nomoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomoreActionPerformed

    private void appgendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appgendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appgendActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     table_load2();        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
 String userid = appid.getText();
         
         dbConnector dbc = new dbConnector();
        
        try{
            if(dbc.deleteData("DELETE FROM applicantstab WHERE id = '"+userid+"' ")){
            
                JOptionPane.showMessageDialog(null, "Data Deleted");
            }
              
            
        } catch (Exception e){
            
            System.out.println(e);

        }  
        
        table_load2();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
             String ids = appid.getText();
        String firstnames = appfirst.getText();
        String lastnames = applast.getText();
        String middlenames = appmid.getText();  
        String contactnum = appcont.getText();
        String emails = appemail.getText();
        String addresss = appaddress.getText();
        String mothername = appmads.getText();
        String fathername = apppads.getText();
        String genders = appgend.getSelectedItem().toString();
        String scholarshiptype = apptype.getSelectedItem().toString();
        String Stat = appstats.getSelectedItem().toString();
        
       
          
        
        try{
            dbConnector dbc = new dbConnector();
         
            
            if(appfirst.getText().isEmpty() || applast.getText().isEmpty() || appmid.getText().isEmpty()||
               appcont.getText().isEmpty()|| appemail.getText().isEmpty()|| appaddress.getText().isEmpty()||
               appmads.getText().isEmpty()|| apppads.getText().isEmpty()|| appyear.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "fields required!");
            }else{
                String query = "UPDATE applicantstab SET fname ='" + firstnames + "', "
                + " lname ='"+lastnames+"', middle_initial ='" + middlenames + "', "
                + " contact_number ='" + contactnum + "',email_address ='" +emails + "', "
                + " adress ='" + addresss + "', mother_name ='" + mothername + "' , "
                + " father_name ='"+ fathername +"', gender='"+ genders +"',"
                + " scholarship_type ='" +scholarshiptype +  "',"
                + " Status ='" + Stat + "' WHERE id ='" + ids + "'";
                
                dbc.insertData(query);
                JOptionPane.showMessageDialog(null, "Data Updated");
            
            }
           
             } catch (Exception e) {
            System.out.println(e);
            }
        
        table_load2();
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bbkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbkActionPerformed
       admindash ads = new admindash();
       ads.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_bbkActionPerformed

    private void bbkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbkMouseEntered
       bbk.setBackground(Color.red); 
    }//GEN-LAST:event_bbkMouseEntered

    private void bbkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbkMouseExited
       bbk.setBackground(Color.white); 
    }//GEN-LAST:event_bbkMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        appid.setText("");
           applast.setText("");
           appfirst.setText("");
           appmid.setText("");
           appcont.setText("");
           appemail.setText("");
           appaddress.setText("");
           appmads.setText("");
           apppads.setText("");
           appyear.setText("");
           appgend.setSelectedItem("");
           apptype.setSelectedItem("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       MessageFormat header = new MessageFormat("Bergen Scholarship University");
       MessageFormat footer = new MessageFormat("All Rights Reserved");
       
        try{
        
            tabs2.print(JTable.PrintMode.FIT_WIDTH,header,footer);
            
        }catch(Exception e){
        
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminapp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField appaddress;
    private javax.swing.JTextField appcont;
    private javax.swing.JTextField appemail;
    private javax.swing.JTextField appfirst;
    private javax.swing.JComboBox<String> appgend;
    private javax.swing.JLabel appid;
    private javax.swing.JTextField applast;
    private javax.swing.JTextField appmads;
    private javax.swing.JTextField appmid;
    private javax.swing.JTextField apppads;
    private javax.swing.JComboBox<String> appstats;
    private javax.swing.JComboBox<String> apptype;
    private javax.swing.JTextField appyear;
    private javax.swing.JButton bbk;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomore;
    private javax.swing.JTable tabs2;
    private javax.swing.JLabel yet;
    // End of variables declaration//GEN-END:variables
}
