/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontdeskdash;

import form.applicationform;
import java.awt.Color;
import javax.swing.JOptionPane;
import login.loginform;

/**
 *
 * @author wangs
 */
public class dashfront extends javax.swing.JFrame {

    /**
     * Creates new form dashfront
     */
    public dashfront() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sd = new javax.swing.JButton();
        st = new javax.swing.JButton();
        td = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nemo = new javax.swing.JLabel();
        nemo2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("Bergen Scholarship University");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(270, 0, 560, 70);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Frontdesk DashBoard");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(300, 50, 410, 70);

        sd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/icons8-students-100.png"))); // NOI18N
        sd.setText("Manage Students");
        sd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sdMouseExited(evt);
            }
        });
        sd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdActionPerformed(evt);
            }
        });
        jPanel1.add(sd);
        sd.setBounds(310, 340, 260, 80);

        st.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        st.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/icons8-scholar-64.png"))); // NOI18N
        st.setText("ADD Student");
        st.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stMouseExited(evt);
            }
        });
        st.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stActionPerformed(evt);
            }
        });
        jPanel1.add(st);
        st.setBounds(340, 220, 200, 80);

        td.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/icons8-x-50.png"))); // NOI18N
        td.setText("Logout");
        td.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tdMouseExited(evt);
            }
        });
        td.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdActionPerformed(evt);
            }
        });
        jPanel1.add(td);
        td.setBounds(690, 630, 150, 29);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("WELCOME:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 140, 110, 20);

        nemo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(nemo);
        nemo.setBounds(170, 130, 100, 40);

        nemo2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(nemo2);
        nemo2.setBounds(230, 130, 90, 40);

        jLabel5.setBackground(new java.awt.Color(153, 153, 153));
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Brown and Beige Blank Notes Landscape A4 Document_1.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 850, 690);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void stMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stMouseEntered
       st.setBackground(Color.green);
    }//GEN-LAST:event_stMouseEntered

    private void stMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stMouseExited
       st.setBackground(Color.white);
    }//GEN-LAST:event_stMouseExited

    private void sdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sdMouseEntered
        sd.setBackground(Color.blue);
    }//GEN-LAST:event_sdMouseEntered

    private void sdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sdMouseExited
       sd.setBackground(Color.white);
    }//GEN-LAST:event_sdMouseExited

    private void stActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stActionPerformed
        applicationform ads = new applicationform();
        ads.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_stActionPerformed

    private void tdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tdMouseEntered
        td.setBackground(Color.red);
    }//GEN-LAST:event_tdMouseEntered

    private void tdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tdMouseExited
        td.setBackground(Color.white);
    }//GEN-LAST:event_tdMouseExited

    private void tdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdActionPerformed
        JOptionPane.showMessageDialog(null,"Logout Successfully as Frontdesk!");
        loginform ads = new loginform();
        ads.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tdActionPerformed

    private void sdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdActionPerformed
        editfrontdesk sad = new editfrontdesk();
        sad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashfront.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashfront.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashfront.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashfront.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashfront().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel nemo;
    public javax.swing.JLabel nemo2;
    private javax.swing.JButton sd;
    private javax.swing.JButton st;
    private javax.swing.JButton td;
    // End of variables declaration//GEN-END:variables
}
