/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userdisplay;

import adminfolder.admindash;
import java.awt.Color;

/**
 *
 * @author wangs
 */
public class userupdate extends javax.swing.JFrame {

    /**
     * Creates new form userupdate
     */
    public userupdate() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        gen = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        j = new javax.swing.JLabel();
        display_id = new javax.swing.JLabel();
        jjj = new javax.swing.JLabel();
        jj = new javax.swing.JLabel();
        jjjj = new javax.swing.JLabel();
        upl_name = new javax.swing.JTextField();
        upcontact = new javax.swing.JTextField();
        upmail = new javax.swing.JTextField();
        upf_name = new javax.swing.JTextField();
        ex = new javax.swing.JButton();
        papas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(765, 644));
        jPanel1.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel13.setText("ID NO: ");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(170, 10, 80, 20);

        gen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        gen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genActionPerformed(evt);
            }
        });
        jPanel1.add(gen);
        gen.setBounds(490, 260, 78, 26);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Gender");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(420, 260, 70, 20);

        j.setText("Firstname:");
        jPanel1.add(j);
        j.setBounds(280, 70, 100, 20);

        display_id.setText("jLabel1");
        jPanel1.add(display_id);
        display_id.setBounds(250, 10, 51, 20);

        jjj.setText("Email:");
        jPanel1.add(jjj);
        jjj.setBounds(330, 150, 100, 20);

        jj.setText("Lastname:");
        jPanel1.add(jj);
        jj.setBounds(300, 120, 100, 20);

        jjjj.setText("Contact #:");
        jPanel1.add(jjjj);
        jjjj.setBounds(320, 190, 100, 20);
        jPanel1.add(upl_name);
        upl_name.setBounds(370, 110, 130, 26);
        jPanel1.add(upcontact);
        upcontact.setBounds(400, 190, 120, 26);

        upmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upmailActionPerformed(evt);
            }
        });
        jPanel1.add(upmail);
        upmail.setBounds(380, 150, 120, 26);
        jPanel1.add(upf_name);
        upf_name.setBounds(370, 70, 130, 26);

        ex.setText("Back");
        ex.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exMouseExited(evt);
            }
        });
        ex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exActionPerformed(evt);
            }
        });
        jPanel1.add(ex);
        ex.setBounds(660, 600, 65, 29);

        papas.setText("Update");
        papas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                papasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                papasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                papasMouseExited(evt);
            }
        });
        jPanel1.add(papas);
        papas.setBounds(480, 330, 93, 29);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\wangs\\Downloads\\pexels-thought-catalog-317580-904616.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 770, 640);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void genActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genActionPerformed

    private void upmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upmailActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void exActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exActionPerformed
          displayuser ads = new displayuser();
          ads.setVisible(true);
    }//GEN-LAST:event_exActionPerformed

    private void papasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_papasMouseClicked
            // TODO add your handling code here:
    }//GEN-LAST:event_papasMouseClicked

    private void papasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_papasMouseEntered
        papas.setBackground(Color.green);
    }//GEN-LAST:event_papasMouseEntered

    private void papasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_papasMouseExited
       papas.setBackground(Color.white);        // TODO add your handling code here:
    }//GEN-LAST:event_papasMouseExited

    private void exMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exMouseEntered
      ex.setBackground(Color.red);        // TODO add your handling code here:
    }//GEN-LAST:event_exMouseEntered

    private void exMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exMouseExited
      ex.setBackground(Color.white);        // TODO add your handling code here:
    }//GEN-LAST:event_exMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userupdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel display_id;
    private javax.swing.JButton ex;
    public javax.swing.JComboBox<String> gen;
    public javax.swing.JLabel j;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel jj;
    public javax.swing.JLabel jjj;
    public javax.swing.JLabel jjjj;
    private javax.swing.JButton papas;
    public javax.swing.JTextField upcontact;
    public javax.swing.JTextField upf_name;
    public javax.swing.JTextField upl_name;
    public javax.swing.JTextField upmail;
    // End of variables declaration//GEN-END:variables
}
